databases:
  - name: rails_tutorial
    databaseName: rails_tutorial_nsgu
    user: rails_tutorial_nsgu_user
    plan: free

services:
  - type: web
    name: rails_tutorial
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_tutorial
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default