databases:
  - name: rails_tutorial
    databaseName: rails_tutorial_nsgu
    user: rails_tutorial_nsgu_user
    region: singapore

services:
  - type: web
    name: rails_tutorial
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
